spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo-db?useUnicode=yes&characterEncoding=utf8
    username: root
    password: root

  session:
    store-type: none


server:
  port: 8060

security:
  basic:
    enabled: false